general:
  delete_log_file_at_start: true # better to leave this true or it will grow quite big
  callsign: YOUR_CALL # Log4OM Callsign used to check if you get spotted by someone
  log_to_file: true
  log_level: DEBUG # INFO or DEBUG or WARN
  telnetserver: true # not in use for now
  flexradiospot: true # not in use for now
database:
  mysql: false #only one of the two can be true
  sqlite: true
  mysql_db_user: user_db_login
  mysql_db_password: user_db_pass
  mysql_db_name: log
  mysql_host: 127.0.0.1
  mysql_port: 3306
sqlite:
  sqlite_path: 'C:\Perso\Seafile\Radio\Logs\Log4OM\F4BPO.SQLite' # SQLite Db path of Log4OM, required if sqlite is true
cluster:
  server: dxc.k0xm.net # dxc.k0xm.net dxc.sm7iun.se
  port: 7300
  login: YOUR_CALL #telnet login
  password: ****** # only if needed else keep blank
  skimmer: true #announce cw spots from RBN
  ft8: false #announce FT8 spots from pskreporter
  ft4: false #announce FT4 spots from pskreporter
  command: "SH/DX 30" #any command you want to send to the dx cluster server you connect to
  login_prompt: "Please enter your call:" #login prompt of the cluster you connect to so the program can send your call
flex:
  discovery: false # Radio must be on same LAN than the program
  ip: 192.168.1.1 # if discovery is true no need to put an IP, can be local IP or remote
  spot_life: 600 #seconds
telnetserver: #You can connect Log4OM to this server if you want, it will replicate the spots received from the cluster under cluster section: 127.0.0.1:7301
  host: 0.0.0.0
  port: 7301 # port for the telnet server
gotify:
  enable: false
  url: https://gotify.tld.com/message
  token: ****** #token from Gotify
  NewDXCC: false
  NewBand: false
  NewMode: false
  NewBandAndMode: false
log4om: # Send calls clicked on panadapter to Log4OM, need to enable remote control in Connections settings and define a port (default is 2241) in Log4OM
  log4om_enable: true
  log4om_ip: 127.0.0.1 # if Log4OM is running on same pc as FlexDXCluster
  remote_port: 2241



